### ISSUE TITLE
README should briefly describe strategies for updating the codebase

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/upgrade#1]
I think a few people might be getting confused, thinking that this script upgrades their _code_ as well as their database.

We should have something in the README that mentions updating the codebase _first_, and then outlines a few strategies.  Namely:

Option A: [Set up the main repo as an upstream of their project](https://help.github.com/articles/configuring-a-remote-for-a-fork), and then [use `git merge` to merge their code with the new codebase](https://help.github.com/articles/syncing-a-fork/).  This requires understanding how to resolve merge conflicts.  I'm not sure how many conflicts it would generate for 0.3.0 -> 0.3.1, but it'd be worth one of us checking out.

Option B: Fresh install, then manually merge in their custom code.  This might be easier for certain projects and certain versions of UF.

**Comment by Netrilix** [comment]
I wouldn't think UserFrosting should generate any merge conflicts since it's a fast-forward, not a separate branch. The only merge conflicts should be users' own edits to core UF files (I'd imagine mostly in the routes).

**Comment by Netrilix** [comment]
Could I get a second set of eyes on this README.md: https://github.com/userfrosting/Upgrade/tree/dev

I'm ready to push that as the new master, I just hate being the only person to look at something before it goes live.
